version: "3"
services:
  dind:
    image: docker:dind
    container_name: gitlab-runner-dind
    privileged: true
    environment:
      DOCKER_DRIVER: overlay2
      DOCKER_HOST: tcp://0.0.0.0:2375
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - gitlab-runner-dind-vol:/var/lib/docker
    restart: unless-stopped

  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    env_file: .env
    environment:
      GITLAB_URL: https://gitlab.com/
      DOCKER_HOST: tcp://dind:2375
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - "gitlab-runner-config:/etc/gitlab-runner"
      - "./runner_register.sh:/work/runner_register.sh"
    working_dir: /work
    depends_on:
      - dind
    restart: unless-stopped

volumes:
  gitlab-runner-config:
    name: gitlab-runner-config
  gitlab-runner-dind-vol:
    name: gitlab-runner-dind-vol
